[package]
name = "sqlx-postgres"
version = "0.6.0-pre"
repository = "https://github.com/launchbadge/sqlx"
description = "PostgreSQL database driver for SQLx, the Rust SQL Toolkit."
license = "MIT OR Apache-2.0"
edition = "2018"
keywords = ["postgres", "sqlx", "database"]
categories = ["database", "asynchronous"]
authors = [
    "LaunchBadge <contact@launchbadge.com>"
]

[package.metadata.docs.rs]
# > RUSTDOCFLAGS="--cfg doc_cfg" cargo +nightly doc --all-features --no-deps --open
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]

[features]
default = []

# blocking (std) runtime
blocking = ["sqlx-core/blocking"]

# async runtime
async = ["futures-util", "sqlx-core/async", "futures-io"]

[dependencies]
atoi = "0.4.0"
sqlx-core = { version = "0.6.0-pre", path = "../sqlx-core" }
futures-util = { version = "0.3.8", optional = true }
log = "0.4.11"
either = "1.6.1"
bytestring = "1.0.0"
url = "2.2.0"
hex = "0.4.3"
percent-encoding = "2.1.0"
futures-io = { version = "0.3", optional = true }
bytes = "1.0"
memchr = "2.3"
bitflags = "1.2"
base64 = "0.13.0"
md-5 = "0.9.1"
itoa = "0.4.7"
paste = "1.0.5"

[dev-dependencies]
sqlx-core = { version = "0.6.0-pre", path = "../sqlx-core", features = ["_mock"] }
sqlx-test = { path = "../sqlx-test" }
futures-executor = "0.3.8"
anyhow = "1.0.37"
conquer-once = "0.3.2"
tokio = { version = "1.0", features = ["full"] }

[[test]]
name = "postgres-connection"
path = "tests/connection.rs"
required-features = ["async", "sqlx-core/tokio"]
