[package]
name = "sqlx-postgres"
version = "0.0.0"
authors = ["Ryan Leckey <leckey.ryan@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "PostgreSQL database driver for dbx."
edition = "2018"

[dependencies]
sqlx-core = { path = "../sqlx-core" }
sqlx-postgres-protocol = { path = "../sqlx-postgres-protocol" }
runtime = "=0.3.0-alpha.6"
futures-preview = "=0.3.0-alpha.17"
byteorder = "1.3.2"
log = "0.4.7"
hex = "0.3.2"
bytes = "0.4.12"
memchr = "2.2.1"
md-5 = "0.8.0"

[dev-dependencies]
matches = "0.1.8"
