[workspace]
members = [
    ".",
    "sqlx-core",
    "sqlx-macros",
    "examples/realworld-postgres"
]

[package]
name = "sqlx"
version = "0.1.1"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/launchbadge/sqlx"
documentation = "https://docs.rs/sqlx"
description = "ðŸ§° The Rust SQL Toolkit."
edition = "2018"
authors = [
    "Ryan Leckey <leckey.ryan@gmail.com>", # ryan@launchbadge.com
    "Austin Bonander <austin.bonander@gmail.com>", # austin@launchbadge.com
    "Zachery Gyurkovitz <zgyurkovitz@gmail.com>", # zach@launchbadge.com
    "Daniel Akhterov <akhterovd@gmail.com>", # daniel@launchbadge.com
]

[features]
default = [ "macros" ]
macros = [ "sqlx-macros", "proc-macro-hack" ]

# database
postgres = [ "sqlx-core/postgres", "sqlx-macros/postgres" ]
mysql = [ "sqlx-core/mysql", "sqlx-macros/mysql" ]

# types
chrono = [ "sqlx-core/chrono", "sqlx-macros/chrono" ]
uuid = [ "sqlx-core/uuid", "sqlx-macros/uuid" ]

[dependencies]
sqlx-core = { version = "0.1.1", path = "sqlx-core" }
sqlx-macros = { version = "0.1.1", path = "sqlx-macros", optional = true }
proc-macro-hack = { version = "0.5.11", optional = true }

[dev-dependencies]
anyhow = "1.0.25"
futures = "0.3.1"
async-std = { version = "1.2.0", features = [ "attributes" ] }
dotenv = "0.15.0"

[[test]]
name = "postgres-macros"
required-features = [ "postgres", "macros" ]

[[test]]
name = "mysql"
required-features = [ "mysql" ]

[[test]]
name = "postgres"
required-features = [ "postgres" ]

[[test]]
name = "postgres-types"
required-features = [ "postgres" ]

[[test]]
name = "mysql-types"
required-features = [ "mysql" ]
