[workspace]
members = [
    ".",
    "sqlx-core",
    "sqlx-macros",
    "sqlx-test",
    "examples/listen-postgres",
    "examples/realworld-postgres",
    "examples/todos-postgres",
]

[package]
name = "sqlx"
version = "0.3.0-alpha.1"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/launchbadge/sqlx"
documentation = "https://docs.rs/sqlx"
description = "ðŸ§° The Rust SQL Toolkit. An async, pure Rust SQL crate featuring compile-time checked queries without a DSL. Supports PostgreSQL, MySQL, and SQLite."
edition = "2018"
keywords = [ "database", "sql", "async", "await" ]
categories = [ "database", "asynchronous" ]
authors = [
    "Ryan Leckey <leckey.ryan@gmail.com>", # ryan@launchbadge.com
    "Austin Bonander <austin.bonander@gmail.com>", # austin@launchbadge.com
    "Zachery Gyurkovitz <zgyurkovitz@gmail.com>", # zach@launchbadge.com
    "Daniel Akhterov <akhterovd@gmail.com>", # daniel@launchbadge.com
]

[package.metadata.docs.rs]
features = [ "tls", "postgres", "mysql", "uuid", "chrono" ]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = [ "macros", "runtime-async-std" ]
macros = [ "sqlx-macros" ]
tls = [ "sqlx-core/tls" ]

# runtime
runtime-async-std = [ "sqlx-core/runtime-async-std", "sqlx-macros/runtime-async-std" ]
runtime-tokio = [ "sqlx-core/runtime-tokio", "sqlx-macros/runtime-tokio" ]

# database
postgres = [ "sqlx-core/postgres", "sqlx-macros/postgres" ]
mysql = [ "sqlx-core/mysql", "sqlx-macros/mysql" ]
sqlite = [ "sqlx-core/sqlite", "sqlx-macros/sqlite" ]

# types
bigdecimal = ["sqlx-core/bigdecimal_bigint", "sqlx-macros/bigdecimal"]
chrono = [ "sqlx-core/chrono", "sqlx-macros/chrono" ]
uuid = [ "sqlx-core/uuid", "sqlx-macros/uuid" ]

[dependencies]
sqlx-core = { version = "0.3.0-alpha.1", path = "sqlx-core", default-features = false }
sqlx-macros = { version = "0.3.0-alpha.1", path = "sqlx-macros", default-features = false, optional = true }

[dev-dependencies]
anyhow = "1.0.26"
futures = "0.3.4"
env_logger = "0.7.1"
async-std = { version = "1.5.0", features = [ "attributes" ] }
tokio = { version = "0.2.13", features = [ "full" ] }
dotenv = "0.15.0"
trybuild = "1.0.24"
sqlx-test = { path = "./sqlx-test" }
paste = "0.1.7"

[[test]]
name = "postgres-macros"
required-features = [ "postgres", "macros" ]

[[test]]
name = "mysql-macros"
required-features = [ "mysql", "macros" ]

[[test]]
name = "sqlite"
required-features = [ "sqlite" ]

[[test]]
name = "sqlite-macros"
required-features = [ "sqlite" ]

[[test]]
name = "sqlite-raw"
required-features = [ "sqlite" ]

[[test]]
name = "sqlite-derives"
required-features = [ "sqlite", "macros" ]

[[test]]
name = "sqlite-types"
required-features = [ "sqlite" ]

[[test]]
name = "mysql"
required-features = [ "mysql" ]

[[test]]
name = "mysql-raw"
required-features = [ "mysql" ]

[[test]]
name = "mysql-derives"
required-features = [ "mysql", "macros" ]

[[test]]
name = "postgres"
required-features = [ "postgres" ]

[[test]]
name = "postgres-raw"
required-features = [ "postgres" ]

[[test]]
name = "postgres-types"
required-features = [ "postgres" ]

[[test]]
name = "postgres-derives"
required-features = [ "postgres", "macros" ]

[[test]]
name = "mysql-types"
required-features = [ "mysql" ]
