[workspace]
members = [
    ".",
    "sqlx-core",
    "sqlx-postgres-protocol",
    "sqlx-postgres",
]

[package]
name = "sqlx"
version = "0.0.0"
authors = ["Ryan Leckey <leckey.ryan@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Asynchronous and expressive database client in pure Rust."
edition = "2018"

[dependencies]
runtime = "=0.3.0-alpha.6"
sqlx-core = { path = "sqlx-core" }
sqlx-postgres = { path = "sqlx-postgres" }
env_logger = "0.6.2"
bytes = "0.4.12"

[profile.bench]
lto = true
codegen-units = 1
incremental = false

[profile.release]
lto = true
codegen-units = 1
incremental = false
