[workspace]
members = [
    ".",
    "sqlx-core",
    "sqlx-macros",
    "examples/realworld-postgres",
    "examples/todos-postgres",
]

[package]
name = "sqlx"
version = "0.2.5"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/launchbadge/sqlx"
documentation = "https://docs.rs/sqlx"
description = "ðŸ§° The Rust SQL Toolkit."
edition = "2018"
keywords = [ "database", "sql", "async", "await" ]
categories = [ "database", "asynchronous" ]
authors = [
    "Ryan Leckey <leckey.ryan@gmail.com>", # ryan@launchbadge.com
    "Austin Bonander <austin.bonander@gmail.com>", # austin@launchbadge.com
    "Zachery Gyurkovitz <zgyurkovitz@gmail.com>", # zach@launchbadge.com
    "Daniel Akhterov <akhterovd@gmail.com>", # daniel@launchbadge.com
]

[package.metadata.docs.rs]
features = [ "tls", "postgres", "mysql", "uuid", "chrono", "time" ]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = [ "macros", "runtime-async-std" ]
macros = [ "sqlx-macros" ]
tls = [ "sqlx-core/tls" ]

# runtime
runtime-async-std = [ "sqlx-core/runtime-async-std", "sqlx-macros/runtime-async-std" ]
runtime-tokio = [ "sqlx-core/runtime-tokio", "sqlx-macros/runtime-tokio" ]

# database
postgres = [ "sqlx-core/postgres", "sqlx-macros/postgres" ]
mysql = [ "sqlx-core/mysql", "sqlx-macros/mysql" ]

# types
chrono = [ "sqlx-core/chrono", "sqlx-macros/chrono" ]
time = [ "sqlx-core/time", "sqlx-macros/time" ]
uuid = [ "sqlx-core/uuid", "sqlx-macros/uuid" ]

[dependencies]
sqlx-core = { version = "0.2.5", path = "sqlx-core", default-features = false }
sqlx-macros = { version = "0.2.4", path = "sqlx-macros", default-features = false, optional = true }

[dev-dependencies]
anyhow = "1.0.26"
futures = "0.3.1"
env_logger = "0.7.1"
async-std = { version = "1.4.0", features = [ "attributes" ] }
tokio = { version = "0.2.9", features = [ "full" ] }
dotenv = "0.15.0"
trybuild = "1.0"

[[test]]
name = "postgres-macros"
required-features = [ "postgres", "macros" ]

[[test]]
name = "mysql-macros"
required-features = [ "mysql", "macros" ]

[[test]]
name = "mysql"
required-features = [ "mysql" ]

[[test]]
name = "postgres"
required-features = [ "postgres" ]

[[test]]
name = "postgres-types"
required-features = [ "postgres" ]

[[test]]
name = "postgres-types-chrono"
required-features = [ "postgres", "chrono" ]

[[test]]
name = "postgres-types-time"
required-features = [ "postgres", "time" ]

[[test]]
name = "mysql-types"
required-features = [ "mysql" ]

[[test]]
name = "mysql-types-chrono"
required-features = [ "mysql", "chrono", "macros" ]

[[test]]
name = "mysql-types-time"
required-features = [ "mysql", "time", "macros" ]

[[test]]
name = "derives"
required-features = [ "macros" ]

[profile.release]
lto = true
