[package]
name = "sqlx"
version = "0.0.0"
authors = ["Ryan Leckey <leckey.ryan@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Asynchronous and expressive database client in pure Rust."
edition = "2018"

[dependencies]
byteorder = "1.3.2"
bytes = "0.4.12"
env_logger = "0.6.2"
futures-preview = "=0.3.0-alpha.17"
hex = "0.3.2"
itoa = "0.4.4"
log = "0.4.7"
md-5 = "0.8.0"
memchr = "2.2.1"
runtime = "=0.3.0-alpha.6"
