[package]
name = "sqlx-mysql"
version = "0.6.0-pre"
repository = "https://github.com/launchbadge/sqlx"
description = "MySQL database driver for SQLx, the Rust SQL Toolkit."
license = "MIT OR Apache-2.0"
edition = "2018"
keywords = ["mysql", "sqlx", "database"]
categories = ["database", "asynchronous"]
authors = ["LaunchBadge <contact@launchbadge.com>"]

[package.metadata.docs.rs]
# > RUSTDOCFLAGS="--cfg doc_cfg" cargo +nightly doc --all-features --no-deps --open
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]

[features]
default = []

# blocking (std) runtime
blocking = ["sqlx-core/blocking"]

# async runtime
async = ["futures-util", "sqlx-core/async", "futures-io"]

[dependencies]
sqlx-core = { version = "0.6.0-pre", path = "../sqlx-core" }
futures-util = { version = "0.3.8", optional = true }
either = "1.6.1"
log = "0.4.11"
bytestring = "1.0.0"
url = "2.2.0"
percent-encoding = "2.1.0"
futures-io = { version = "0.3", optional = true }
bytes = "1.0"
memchr = "2.3"
bitflags = "1.2"
sha-1 = "0.9.2"
sha2 = "0.9.2"
rsa = "0.3.0"
base64 = "0.13.0"
rand = "0.7"

[dev-dependencies]
sqlx-core = { version = "0.6.0-pre", path = "../sqlx-core", features = ["_mock", "tokio"] }
futures-executor = "0.3.8"
anyhow = "1.0.37"
tokio = { version = "1.0", features = ["full"] }
once_cell = "1.5.2"

[[test]]
name = "mysql-connection"
path = "tests/connection.rs"
required-features = ["async"]
