[package]
name = "sqlx-example-postgres-todos"
version = "0.1.0"
edition = "2018"
workspace = "../../../"

[dependencies]
anyhow = "1.0"
async-std = { version = "1.4.0", features = [ "attributes" ] }
futures = "0.3"
paw = "1.0"
sqlx = { path = "../../../", features = ["postgres", "offline"] }
structopt = { version = "0.3", features = ["paw"] }
dotenv = "0.15.0"
