[package]
name = "sqlx-example-postgres-transaction"
version = "0.1.0"
edition = "2021"
workspace = "../../../"

[dependencies]
sqlx = { path = "../../../", features = [ "postgres", "runtime-tokio", "tls-native-tls" ] }
futures = "0.3.1"
tokio = { version = "1.20.0", features = ["rt-multi-thread", "macros"]}
